@host = localhost:8080
@baseUrl = http://{{host}}/v1
@contentType = application/json


### Health check
GET {{baseUrl}}/health
Accept: {{contentType}}

### Create Post
POST {{baseUrl}}/posts
Content-Type: {{contentType}}

{
  "title": "New title",
  "content" : "Hey this is my first post =D",
  "tags": ["tag1"]
}

### ── Variables  ────────────────────────
@postId = 6

### Get posts by id
GET {{baseUrl}}/posts/{{postId}}


### ── Variables  ────────────────────────
@deletePostId = 5

### Delete posts by id
DELETE  {{baseUrl}}/posts/{{deletePostId}}


### ── Variables  ────────────────────────
@updatePostId = 6

### Update Post
PATCH  {{baseUrl}}/posts/{{updatePostId}}
Content-Type: {{contentType}}

{
  "title": "HELLO WORLD"
}


### ── Variables  ────────────────────────
@userId = 6

### Get users by id
GET {{baseUrl}}/users/{{userId}}
