@host = localhost:8080
@baseUrl = http://{{host}}/v1
@contentType = application/json


### Health check
GET {{baseUrl}}/health
Accept: {{contentType}}

### Create Post
POST {{baseUrl}}/posts
Content-Type: {{contentType}}

{
  "title": "New title",
  "content" : "Hey this is my first post =D",
  "tags": ["tag1"]
}
